### ISSUE TITLE
PostDashboardOKBody.id has wrong type (int instead of string

### ISSUE THREAD

**Issue by patst** [grafana/grafana-openapi-client-go#16]
**Describe the bug**
I am using the API Client to update dashboards using the method `grafanaClient.Dashboards.PostDashboard`.

The payload is correct, because I got a 200 response. Unfortunately the response cannot be unmarshalled, because it is expection a string, but the API returns an integer.

**To reproduce**

Import this dashboard into Grafana:
```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 10,
  "links": [],
  "liveNow": false,
  "panels": [],
  "refresh": "",
  "schemaVersion": 38,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Dashboard Test!",
  "uid": "test-uid2",
  "version": 3,
  "weekStart": ""
}
```

Create a new API client and call the PostDashboard API:
```
... // init Grafana Client
params := &dashboards.PostDashboardParams{
		Context: ctx,
		Body: &models.SaveDashboardCommand{
			FolderUID: "test", // leave empty for default folder
			Overwrite: true,
			Dashboard: map[string]interface{} {
				"title": "Dashboard Test 2!",
				"uid": "test-uid",
			},
		},
	}
	_, err = grafanaClient.Dashboards.PostDashboard(params, nil)
```
Response error: 
"json: cannot unmarshal number into Go struct field PostDashboardOKBody.id of type string"

**Expected behavior**
Unmarshalling works.

**Additional context**

Grafana Version: Grafana v10.1.5 (849c612fcb)

Checking the dashboard JSON in the Grafana UI shows the `version`  attribute is an integer.

Checking the generated API client I see it is an string. (see https://github.com/grafana/grafana-openapi-client-go/blob/480147ff8f3d871c826099efc717f28e94290da8/models/post_dashboard_o_k_body.go#L25 )

This seems to be a mismatch which causes the error during unmarshalling.

Infos for the go dependencies:
```
	github.com/grafana/grafana-openapi-client-go v0.0.0-20231017131745-480147ff8f3d
	github.com/go-openapi/loads v0.21.2 // indirect
	github.com/go-openapi/runtime v0.26.0 // indirect
	github.com/go-openapi/spec v0.20.8 // indirect
	github.com/go-openapi/swag v0.22.4 // indirect
	github.com/go-openapi/validate v0.22.1 // indirect
```

The swagger definition (http://localhost:3000/public/api-merged.json) show the id as a string as well, which does match reality.

cURL proves that:
```
curl -v -u "admin:admin" --header "Content-Type: application/json" http://localhost:3000/api/dashboards/db -d '{"dashboard": { "title": "dashboard test 2!", "uid": "test-uid" }, "folderUid": "test", "overwrite": true }'
# response:
{"id":11,"slug":"dashboard-test-2","status":"success","uid":"test-uid","url":"/d/test-uid/dashboard-test-2","version":1}
```

Is this something which was changed in a recent Grafana Version?

**Comment by safaci2000** [comment]
This sounds like it's a valid but have you considered using the 'import' endpoint instead? 

I have this snippet working fine.

```go
		importDashReq := dashboards.NewImportDashboardParams()
		importDashReq.Body = &models.ImportDashboardRequest{
			FolderID:  folderId,
			Overwrite: true,
			Dashboard: data,
		}

		if _, exportError := s.officialClient.Dashboards.ImportDashboard(importDashReq, s.getAuth()); exportError != nil {
			log.WithError(err).Printf("error on Exporting dashboard %s", file)
			continue
		}


```

**Comment by patst** [comment]
> This sounds like it's a valid but have you considered using the 'import' endpoint instead?
> 
> I have this snippet working fine.
> 
> ```go
> 		importDashReq := dashboards.NewImportDashboardParams()
> 		importDashReq.Body = &models.ImportDashboardRequest{
> 			FolderID:  folderId,
> 			Overwrite: true,
> 			Dashboard: data,
> 		}
> 
> 		if _, exportError := s.officialClient.Dashboards.ImportDashboard(importDashReq, s.getAuth()); exportError != nil {
> 			log.WithError(err).Printf("error on Exporting dashboard %s", file)
> 			continue
> 		}
> ```

thanks for your message and example.
Actually I am using the 'import' endpoint for creating the dashboards and the other one for modifying.

I wasn't aware  that modifications work with the import endpoint as well. I did a quick check and it seems to work fine!

I am leaving this issue open anyway, because the PostDashboard endpoint should work as well imho.

**Comment by safaci2000** [comment]
If you look at the network calls on the web interface it mostly uses import.  Also, if you use library panels I believe only import supports pulling those in.

**Comment by nikimanoledaki** [comment]
Hi @patst & @safaci2000, thank you so much for testing & providing feedback for the newly generated Grafana client! 🎉 

@joanlopez opened a [PR](https://github.com/grafana/grafana/pull/76749) recently to fix this:
> It changes the [`postDashboardResponse.id`](https://github.com/grafana/grafana/blob/8b16f2aca88d5b1b8033cd9d70de49ec75dcadfa/pkg/api/dashboard.go#L1286) type from `string` to `int64`, because the `id` it represents [is populated with Dashboard.ID](https://github.com/grafana/grafana/blob/8b16f2aca88d5b1b8033cd9d70de49ec75dcadfa/pkg/api/dashboard.go#L522C1-L523C1) which [is an `int64`](https://github.com/grafana/grafana/blob/455cede6992cfad57f1c5b1749c9454d1475dba6/pkg/services/dashboards/models.go#L31).

This is going into Grafana v10.3.0 but we could backport it.

Also, the client is currently generating against Grafana v10.0.1 so we're looking into which version is best to upgrade to.

Thank you for your patience while we set up processes around this! Hopefully we'll have this fixed very soon 😄 👍

**Comment by nikimanoledaki** [comment]
Update: We will keep the client's `main` branch synced with Grafana's latest version. For now, we merged a PR that does this (manually, until we add automation), so `main` is now synced with Grafana v10.2.0. 

It would be nice to keep branches of the client and/or do client releases for different Grafana releases :) Let us know if that would be helpful.

To unblock you until the next patch release, I generated the client against grafana's `main` branch and pushed this to the [grafana-main](https://github.com/grafana/grafana-openapi-client-go/tree/grafana-main) branch. 

We can sync this branch periodically (manually for now). This could be helpful for dev / testing that upstream fixes actually fix things in the client, prior to the next release! 👍

**Comment by safaci2000** [comment]
Yes, very much so.  I can't speak for others, but it's very important to me to know which grafana version the client is based on.  

Ideally, it would be great if a grafana release would trigger a release of the client as well, but at lease if we do releases, having it tagged by the grafana version would be great.  Or at least have a way to determine what grafana version it's based on.
