### ISSUE TITLE
User Search / Listing Not Working.

### ISSUE THREAD

**Issue by safaci2000** [grafana/grafana-openapi-client-go#17]
**Describe the bug**

List users endpoint /api/users fails to return a proper response.

**To reproduce**

```go
params := users.NewSearchUsersParams()
params.Page = tools.PtrOf(int64(1))
params.Perpage = tools.PtrOf(int64(5000))
usersData, err := s.officialClient.Users.SearchUsers(params, s.getAuth())
```

**Expected behavior**
A valid response / payload.  Instead the follow error is returned:

json: cannot unmarshal array into Go value of type models.SearchUserQueryResult

**Comment by nikimanoledaki** [comment]
Hey @safaci2000, thank you for pointing this out! Does this still occur with the latest `main`? Yesterday's PR about the retries reverted the custom changes around how responses are handled to goswagger's default response handling.

**Comment by safaci2000** [comment]
Awesome, this has been resolved.  It's been ongoing for a while.
