### ISSUE TITLE
[BUG] Using the Retry Logic Performance

### ISSUE THREAD

**Issue by safaci2000** [grafana/grafana-openapi-client-go#19]
**Describe the bug**

So, I tried initializing the client as follows:
```go
	httpTransportCfg := client.TransportConfig{
		Host:     u.Host,
		BasePath: "/api",
		Schemes:  []string{u.Scheme},
		NumRetries: 3,
	}
        // 
	if config.Config().IgnoreSSL() {
		httpTransportCfg.TLSConfig =  &tls.Config{InsecureSkipVerify: true}
	}
	if s.grafanaConf.UserName != "" && s.grafanaConf.Password != "" {
		httpTransportCfg.BasicAuth = url.UserPassword(s.grafanaConf.UserName, s.grafanaConf.Password)
	}
	if s.grafanaConf.APIToken != "" {
		httpTransportCfg.APIKey = s.grafanaConf.APIToken
	}
	if s.grafanaConf.OrganizationId != 0 {
		httpTransportCfg.OrgID = s.grafanaConf.OrganizationId
	}

	s.client = client.NewHTTPClientWithConfig(strfmt.Default, &httpTransportCfg)
```	

Most of the options are for reference, the only factor is setting 	NumRetries to a value or not. 

Then running my tool using the API has the following performance difference:

WIth NumRetry = 3

```sh
0.00s user 0.00s system 0% cpu 14.850 total
./bin/gdg backup dashboards upload  0.11s user 0.03s system 0% cpu 14.849 total
```

Without NumRetry being set
```sh
yes  0.00s user 0.00s system 0% cpu 1.328 total
./bin/gdg backup dashboards upload  0.11s user 0.03s system 10% cpu 1.327 total
```

So my understand is that IF the endpoint is successful, it shouldn't affect performance and even if additional work is done, the runtime is 14x slower?   This feels like a bug.

**To reproduce**
Create a client with NumRetries turned on attempt to perform an HTTP request and try again with the option disabled for an endpoint that is accessible.

If helpful, you can run the code here that demonstrates this pattern:  https://github.com/esnet/gdg/tree/feature/switchAPI

**Expected behavior**
Performance to not be degraded when enabling RetryLogic.

**Comment by nikimanoledaki** [comment]
Interesting, I'm wondering if this could be caused by the [backoff](https://github.com/grafana/grafana-openapi-client-go/blob/949fda3a17a0f1a05bda9de9d0f70bd7f1b7d40a/pkg/transport/transport.go#L40) logic, which runs if `NumRetry` is set and `RetryTimeout` is not set.

Could you try testing with `NumRetry` = 3 & `RetryTimeout` to an arbitrary duration e.g. `1s` please?

A PR to improve this is also very welcome and would be very much appreciated! 😄

**Comment by safaci2000** [comment]
2023/10/26 09:59:13 RoundTripper returned a response & error; ignoring response
INFO[0009] it took 10 to import dashboard
INFO[0009] error on Exporting dashboard test/data/org_1/dashboards/Other/dashboard-makeover-challenge.json  error="<nil>"

Okay, this is the intended behavior.  For some reason the json is now giving me a server 500 error.   Is there a pattern to allow for retries on timeout? That would be very useful, even more so than the retry logic.  

Timeout exceptions are a bit more common.

**Comment by safaci2000** [comment]
I'll close this as this is intended behavior.
