### ISSUE TITLE
Support Grafana Cloud

### ISSUE THREAD

**Issue by F21** [grafana/grafana-openapi-client-go#70]
**Is your feature request related to a problem?**
Since https://github.com/grafana/grafana-api-golang-client has been archived this library is to be used as a replacement, it would be great if this library can also support Grafana Cloud API endpoints (which are currently only available in `grafana-api-golang-client`).

**Describe the solution you'd like**
Support Grafana Cloud API endpoints

**Describe alternatives you've considered**
n/a

**Additional context**
There doesn't appear to be any published OpenAPI spec for the Grafana Cloud API at the moment.
API docs: https://grafana.com/docs/grafana-cloud/developer-resources/api-reference/cloud-api/

**Comment by julienduchesne** [comment]
👋. You can use the client here: https://github.com/grafana/grafana-com-public-clients. It supports more endpoints than the archived client did
