### ISSUE TITLE
DataSource Permission Endpoints not being generated

### ISSUE THREAD

**Issue by safaci2000** [grafana/grafana-openapi-client-go#80]
**Describe the bug**
The latest version seems to have the 'datasource_permissions' namespace missing.  This includes:

POST datasources/{connectionID}/disable-permission
POST datasource{connectionID}/enable-permission
GET datasource/{connectionID}/permission
POST datasource/{connectionID}/permission
DELETE datasource/{connectionID}/permission

**To reproduce**
simply trying to use any of the APIs listed above.

**Expected behavior**
The OpenAPI to have a valid client to use to set/disable permission.  
**Screenshots**
![Screenshot 2024-03-04 at 3 06 00 PM](https://github.com/grafana/grafana-openapi-client-go/assets/62894/5147b781-aa89-41ab-9702-7303bd64e287)

Confirmed that it's available on latest version.

**Comment by csg33k** [comment]
They're also available under "enterprise" tag and are also missing from there.

**Comment by csg33k** [comment]
Found the reason why the end points were missing.  :-( 

```
The following data source permission endpoints have been removed:

- `GET /datasources/:datasourceId/permissions`
- `POST /api/datasources/:datasourceId/permissions`
- `DELETE /datasources/:datasourceId/permissions`
- `POST /datasources/:datasourceId/enable-permissions`
- `POST /datasources/:datasourceId/disable-permissions`

Please use the following endpoints instead:

- `GET /api/access-control/datasources/:uid` for listing data source permissions
- `POST /api/access-control/datasources/:uid/users/:id`, `POST /api/access-control/datasources/:uid/teams/:id` and `POST /api/access-control/datasources/:uid/buildInRoles/:id` for adding or removing data source permissions
```

**Comment by safaci2000** [comment]
Found the reason why the end points were missing.  :-( 

```
The following data source permission endpoints have been removed:

- `GET /datasources/:datasourceId/permissions`
- `POST /api/datasources/:datasourceId/permissions`
- `DELETE /datasources/:datasourceId/permissions`
- `POST /datasources/:datasourceId/enable-permissions`
- `POST /datasources/:datasourceId/disable-permissions`

Please use the following endpoints instead:

- `GET /api/access-control/datasources/:uid` for listing data source permissions
- `POST /api/access-control/datasources/:uid/users/:id`, `POST /api/access-control/datasources/:uid/teams/:id` and `POST /api/access-control/datasources/:uid/buildInRoles/:id` for adding or removing data source permissions
```
