### ISSUE TITLE
List orgs, then dashboards in org and retrive their variables

### ISSUE THREAD

**Issue by senpro-ingwersenk** [grafana/grafana-openapi-client-go#99]
Hello there!

I am a little lost on how this package is supposed to work. Basically, I don't need much but to fetch a few information from our Grafana instance that I can then send as bulk requests to the [ruby-grafana-reporter](https://github.com/divinity666/ruby-grafana-reporter). The idea is kinda simple; it'd look a little like this in pseudo-code:

```
client := MakeClient(baseUrl, apiToken)
orgs := client.ListAllOrgs()
for org in orgs {
  dashboards := org.ListAllDashboards()
  for dash in dashboards {
    MakeReport(org.Name, dash.Name, dash.Variables)
  }
}
```

I did successfuly create a client but while looking at the dokumentation on the pkg.go.dev page, I couldn't find the methods that I would need to use for this use case.

Do you have a pointer, perhaps?

Thank you and kind regards!

**Comment by safaci2000** [comment]
ListAllDashboards:   GetClient().Search.Search(searchParams)
Reporting: 		GetClient().Reports.CreateReport()

All the methods are based on this: https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/public/api-merged.json 

have a look and see if you can find the right 'call'.  Each section essentially translates to GetClient().Section.Method

this is another resource as well. https://grafana.com/docs/grafana/latest/developers/http_api/

**Comment by senpro-ingwersenk** [comment]
Perfect! Those seem like the resources I needed, thank you :)

**Comment by senpro-ingwersenk** [comment]
I think I am having a blonde moment...

Using BasicAuth (I am using OSS version) I can list all organizations just fine. The dashboards, however, are a different problem:

```
		fmt.Println("Dashboards:")
		dashDsStr := "dash-ds"
		params := search.SearchParams{Type: &dashDsStr}
		dashboards, err := client.WithOrgID(v.ID).Search.Search(&params, nil)
		if err != nil {
			fmt.Println("Couldn't get dashboards")
			fmt.Println(err.Error())
			os.Exit(1)
		}
		for _, vv := range dashboards.GetPayload() {
			fmt.Println(vv.FolderUID + " - " + string(vv.Type) + " - " + vv.Title)
		}
```
(`client` is an instance of the API client, whilst `v` is a `for _,v := range orgs.GetPayload()` instance)

Aside from the odd construction of `params` (I kept running into compile errors, so eventually I just did...this), it also shows me both `dash-folder` and `dash-db`, although I only need the latter.

```
Dashboards:
 - dash-folder - Microsoft Corporation
d7f5f1bc-6a08-4f11-b234-025ca24b7293 - dash-db - Windows (Clients)
d7f5f1bc-6a08-4f11-b234-025ca24b7293 - dash-db - Windows (Server)
```

How do I have it return _only_ the dashboards? Or is there something I am missing?

Thanks!

**Comment by safaci2000** [comment]
so, rather than constructing those params, manually, there's a New() function for each of them that does some nicities.  In this case I think it just sets a default timeout, but I try to use that over defining the struct and letting the swagger do what it needs to.

This is what works for me.

```go
func PtrOf[T any](value T) *T {
	return &value
}

func dostuff() {

		searchParams := search.NewSearchParams()
		searchParams.Limit = tools.PtrOf(limit)
		searchParams.Page = tools.PtrOf(page)
		pageBoardLinks, err := s.GetClient().Search.Search(searchParams)
		searchParams.Type = tools.PtrOf(searchTypeDashboard) // value of searchTypeDashboard: "dash-db"
		pageBoardLinks, err := s.GetClient().Search.Search(searchParams)
}
```

You can look at what I'm doing here if you like, but it's a bit more complicated than you need it to be: https://github.com/esnet/gdg/blob/b02a854a538b1d1b07d7d35c8bb435b91da57b93/internal/service/dashboards.go#L209



The swagger page I linked above should also give you all the drop down options for filtering.
